export { repartir } from "./repartir";
export type { ParteEntrada, ParteRepartida, Reparticao } from "./repartir";
export {
  ANEL_DISCO,
  ESPESSURA,
  OSCILACAO,
  THETA_PARADA,
  METAL,
  COREO,
  faceMoeda,
  geoMoeda,
  posNaFace,
  geoGrelha,
  slotGrelha,
  colsMonte,
  geoMontes,
  slotMonte,
  atribuirSectores,
  atribuirSequencia,
  reatribuir,
  molaPasso,
  molaAssentou,
} from "./layouts";
export type {
  NomeLayout,
  TomParte,
  PartePontos,
  PontoMoeda,
  GeoMoeda,
  GeoGrelha,
  MonteGeo,
  GeoMontes,
  Dono,
  CorpoMola,
} from "./layouts";
